---
- name: Join cluster with self-signed certificate on primary
  effectivelywild.technitium_dns.technitium_dns_init_join_cluster:
    api_url: "{{ technitium_api_url }}"
    api_token: "{{ login_result.token }}"
    secondary_node_ip_addresses:
      - "{{ ansible_host }}"
    primary_node_url: "https://pi1.{{ domain }}:53443/"
    primary_node_ip_address: "{{ hostvars[groups['dns_primary_servers'][0]]['ansible_host'] }}"
    ignore_certificate_errors: true
    primary_node_username: "{{ technitium_username }}"
    primary_node_password: "{{ technitium_password }}"
  register: technitium_join_cluster_result

- name: Display cluster initialization result
  ansible.builtin.debug:
    var: technitium_join_cluster_result
