---
- name: Add A records
  effectivelywild.technitium_dns.technitium_dns_add_record:
    api_url: "{{ technitium_api_url }}"
    api_token: "{{ login_result.token }}"
    name: "{{ item.name }}.{{ domain }}"
    type: "A"
    ipAddress: "{{ item.ipAddress }}"
    ttl: 3600
    validate_certs: false
  loop:
    - name: opnsense
      ipAddress: "192.168.1.1"
    - name: switch
      ipAddress: "192.168.1.10"
    - name: ap
      ipAddress: "192.168.1.11"
    - name: proxmox
      ipAddress: "192.168.1.12"
    - name: minio
      ipAddress: "192.168.1.20"
    - name: speedport
      ipAddress: "192.168.178.1"
    - name: truenas
      ipAddress: "192.168.30.108"
