---
extends: default
rules:
  line-length:
    max: 180
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  document-start: disable
  comments-indentation: disable
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
ignore: |
  vendor/
  .dagger/
  .creds.env.yaml
  .kubeconform.yaml
