[tools]
dagger = "0.20.3"
uv = "latest"

[settings]
python.uv_venv_auto = true

[env]
PROJECT_NAME = "{{ config_root | basename }}"

# _.file = [
#   { path = "{{env.HOME}}/.env", optional = true },
#   { path = ".env", optional = true },
#   { path = ".creds.env.yaml", redact = true }
# ]
_.python.venv = { path = ".venv", create = true }

[hooks]
enter = [
  'echo ""',
  'echo "[MISE] Setup $PROJECT_NAME project..."',
  #
  'mise i -q',
  #
  'pre-commit install -f --hook-type pre-commit',
  #
  'mise run python:install-requirements',
]
