[tools]
dagger = "0.20.3"
uv = "latest"

[settings]
python.uv_venv_auto = true

[env]
PROJECT_NAME = "{{ config_root | basename }}"

_.python.venv = { path = ".venv", create = true }

[hooks]
enter = [
  'echo ""',
  'echo "[MISE] Setup $PROJECT_NAME project..."',
  #
  'mise i -q',
  #
  'mise run pre-commit:install',
  #
  'mise run python:install-requirements',
]
