---
- name: Sync NetBox data to Authentik # noqa: args[module]
  sflab.homelab.authentik_users:
    state: present
  delegate_to: localhost

- name: Create provider
  sflab.homelab.authentik_provider:
    name: "{{ provider.provider_name }}"
    authorization_flow: "{{ provider.authorization_flow }}"
    invalidation_flow: "{{ provider.invalidation_flow }}"
    redirect_uris: "{{ provider.redirect_uris | default([provider.redirect_uri]) }}"
    scopes: "{{ provider.scopes }}"
    signing_key: "{{ provider.signing_key }}"
    state: present
  delegate_to: localhost
  register: authentik_portainer_provider
  loop: "{{ providers }}"
  loop_control:
    loop_var: provider

- name: Create application
  sflab.homelab.authentik_application:
    name: "{{ application.application_name }}"
    slug: "{{ application.application_slug }}"
    provider: "{{ application.provider_name }}"
    state: present
  delegate_to: localhost
  loop: "{{ applications }}"
  loop_control:
    loop_var: application
