---
#
# This task file enables and configures the KV-v2 secrets engine in Vault.
#
# Prerequisites:
# - __vault_secrets_init_data fact must be set (loaded via load_vault_init_data.yml)
# - __vault_secrets_url fact must be set (loaded via load_vault_init_data.yml)
#

- name: Enable KV-v2 secrets engine
  sflab.homelab.vault_kv_secret_engine:
    url: "{{ __vault_secrets_url }}"
    auth_method: "token"
    token: "{{ __vault_secrets_init_data.root_token }}"
    engine_mount_point: "{{ vault_secrets_engine_name }}"
    kv_version: 2
    state: "present"
    validate_certs: "{{ vault_secrets_validate_certs }}"
  no_log: true
