---
- name: Validate
  ansible.builtin.include_tasks: validate/main.yml

- name: Load Vault init data
  ansible.builtin.include_tasks: load_vault_init_data.yml

- name: Configure secrets engine
  ansible.builtin.include_tasks: configure_secrets_engine.yml

- name: Configure policy
  ansible.builtin.include_tasks: configure_policy.yml

- name: Configure appRole
  ansible.builtin.include_tasks: configure_approle.yml

- name: Output appRole credentials
  ansible.builtin.include_tasks: output_approle_credentials.yml
  when: ansible_verbosity > 0

- name: Initialize secrets data
  ansible.builtin.include_tasks: initialize_secrets_data.yml
