---
# defaults file for sflab.homelab.docker

# Base domain for the reverse proxy
docker_domain: "{{ ansible_host }}"

# Vault PKI ACME directory endpoint URL
docker_vault_acme_endpoint: "https://vault.{{ domain }}/v1/pki_intermediate/acme/directory"

# ACME email address
docker_acme_email: "acme@{{ domain }}"

# Docker network for Traefik
docker_traefik_proxy_network: "proxy"

# Deploy Traefik reverse proxy
docker_deploy_stacks: []

# Remote docker-compose repository URL (HTTPS)
compose_remote_url: ""

# Remote stacks to deploy (list of {name, envs} dicts)
compose_remote_stacks: []
