---
# defaults file for sflab.homelab.docker

# Base domain for the reverse proxy
docker_domain: "{{ ansible_host }}"

# Vault PKI ACME directory endpoint URL
docker_vault_acme_endpoint: "https://vault.{{ domain }}:8200/v1/pki_intermediate/acme/directory"

# ACME email address
docker_acme_email: "acme@{{ domain }}"

# Deploy Traefik reverse proxy
docker_deploy_traefik: true

# Docker network for Traefik
docker_traefik_proxy_network: "proxy"

# Deploy Portainer container management UI
# Accessible via: https://portainer.{{ docker_domain }}
docker_deploy_portainer: true
