---
#
# This task file configures the intermediate CA PKI secret engine in Vault for ACME support.
#
# Prerequisites:
# - __pki_vault_init_data fact must be set (loaded via load_vault_init_data.yml)
#

# - name: Debug variables
#   ansible.builtin.debug:
#     msg: |
#       Configuring PKI Intermediate CA with the following parameters:
#         __pki_vault_url: {{ __pki_vault_url }}
#         pki_intermediate_mount_point: {{ pki_intermediate_mount_point }}

- name: Tune PKI intermediate CA for ACME support
  sflab.homelab.vault_secrets_tune:
    url: "{{ __pki_vault_url }}"
    auth_method: "token"
    token: "{{ __pki_vault_init_data.root_token }}"
    engine_mount_point: "{{ pki_intermediate_mount_point }}"
    passthrough_request_headers:
      - If-Modified-Since
    allowed_response_headers:
      - Last-Modified
      - Location
      - Replay-Nonce
      - Link

- name: Configure ACME support in PKI intermediate CA
  sflab.homelab.vault_write:
    url: "{{ __pki_vault_url }}"
    auth_method: "token"
    token: "{{ __pki_vault_init_data.root_token }}"
    path: "{{ pki_intermediate_mount_point }}/config/acme"
    data:
      enabled: true
