---
#
# This task file configures the intermediate CA PKI secret engine in Vault.
#
# Prerequisites:
# - __pki_vault_init_data fact must be set (loaded via load_vault_init_data.yml)
#

# - name: Debug variables
#   ansible.builtin.debug:
#     msg: |
#       Configuring PKI Intermediate CA Secret Engine with parameters:
#         __pki_vault_url: {{ __pki_vault_url }}
#         pki_intermediate_mount_point: {{ pki_intermediate_mount_point }}
#         pki_intermediate_description: {{ pki_intermediate_description }}
#         pki_intermediate_default_lease_ttl: {{ pki_intermediate_default_lease_ttl }}
#         pki_intermediate_max_lease_ttl: {{ pki_intermediate_max_lease_ttl }}
#         pki_intermediate_replace_different_backend: {{ pki_intermediate_replace_different_backend }}

- name: Enable and configure intermediate CA PKI secret engine
  sflab.homelab.vault_pki_secret_engine:
    url: "{{ __pki_vault_url }}"
    auth_method: "token"
    token: "{{ __pki_vault_init_data.root_token }}"
    engine_mount_point: "{{ pki_intermediate_mount_point }}"
    state: "present"
    description: "{{ pki_intermediate_description }}"
    default_lease_ttl: "{{ pki_intermediate_default_lease_ttl }}"
    max_lease_ttl: "{{ pki_intermediate_max_lease_ttl }}"
    replace_different_backend_type: "{{ pki_intermediate_replace_different_backend }}"
  no_log: true # Token in parameters
  register: __pki_intermediate_engine_result
# - name: Display PKI intermediate engine configuration status
#   ansible.builtin.debug:
#     msg: |
#       PKI Intermediate Engine Status:
#         Changed: {{ __pki_intermediate_engine_result.changed }}
#         Mount Point: {{ pki_root_mount_point }}
#         Default Lease TTL: {{ pki_root_default_lease_ttl }}
#         Max Lease TTL: {{ pki_root_max_lease_ttl }}
#   when: __pki_intermediate_engine_result is defined
