---
#
# This task file configures the root CA PKI secret engine in Vault.
#
# Prerequisites:
# - __vault_pki_vault_init_data fact must be set (loaded via load_vault_init_data.yml)
#

- name: Enable and configure root CA PKI secret engine
  sflab.homelab.vault_pki_secret_engine:
    url: "{{ __vault_pki_vault_url }}"
    auth_method: "token"
    token: "{{ __vault_pki_vault_init_data.root_token }}"
    validate_certs: "{{ vault_pki_vault_api_validate_certs }}"
    engine_mount_point: "{{ vault_pki_root_mount_point }}"
    state: "present"
    description: "{{ vault_pki_root_description }}"
    default_lease_ttl: "{{ vault_pki_root_default_lease_ttl }}"
    max_lease_ttl: "{{ vault_pki_root_max_lease_ttl }}"
    replace_different_backend_type: "{{ vault_pki_root_replace_different_backend }}"
