---
# defaults file for sflab.homelab.firewall
firewall_domain: "{{ domain }}"
firewall_ip: "192.168.1.34"

firewall_acme_account_email: "acme@{{ firewall_domain }}"

firewall_acme_url: "https://vault.{{ firewall_domain }}:8200/v1/pki_intermediate/acme/directory"
firewall_dns_nsupdate_server: "192.168.1.13"
firewall_dns_ddns_key_algorithm: "hmac-sha256"

# ---
# this is just printed as a helper after VLANs are configured to remember user for manual interfaces config
firewall_interfaces: []

# this is just printed as a helper after gateways are configured to remember user for manual gateway group config
firewall_gateway_groups: []

firewall_vlans: {}

firewall_gateways: {}

firewall_dhcp: {}

firewall_dhcp_subnets: {}

firewall_dhcp_reservations: {}

firewall_aliases: {}

firewall_nat_outbound: {}

firewall_shaper_pipes: {}

firewall_shaper_queues: {}

firewall_shaper_rules: {}

firewall_rules: {}

firewall_tailscale_advertised_routes: {}
