---
- name: Pulling existing gateways
  oxlorg.opnsense.list:
    target: gateway
  register: firewall_existing_gateways

# - name: Debug print existing gateways
#   ansible.builtin.debug:
#     var: firewall_existing_gateways.data

- name: Purging unconfigured gateways
  # ansible.builtin.debug:
  #   msg: "Purging gateway {{ existing_gateway_id }}"
  oxlorg.opnsense.gateway:
    name: "{{ existing_gateway_id }}"

    match_fields: ["name"]
    state: "absent"
    reload: false

  when: existing_gateway_id not in firewall_gateways

  vars:
    existing_gateway_id: "{{ existing_gateway_item.name }}"

  loop_control:
    loop_var: existing_gateway_item
    label: "{{ existing_gateway_item.name }}"
  with_items: "{{ firewall_existing_gateways.data }}"
  register: firewall_purged_gateways

- name: Creating gateways
  oxlorg.opnsense.gateway:
    name: "{{ gateway_id }}"
    description: "{{ gateway.desc | default(omit) }}"

    interface: "{{ gateway.int | default(omit) }}"
    gateway: "{{ gateway.ip | default(omit) }}"

    default_gw: "{{ gateway.default | default(False) }}"
    far_gw: "{{ gateway.far | default(False) }}"
    priority: "{{ gateway.priority | default(255) }}"
    weight: "{{ gateway.weight | default(1) }}"

    monitor_disable: "{{ gateway.monitor_disable | default(False) }}"
    monitor: "{{ gateway.monitor | default(omit) }}"
    time_period: "{{ gateway.time_period | default(30) }}"
    force_down: "{{ gateway.force_down | default(False) }}"

    match_fields: ["name"]
    state: "present"
    reload: false

  vars:
    gateway: "{{ gateway_item.value }}"
    gateway_id: "{{ gateway_item.key }}"

  loop_control:
    loop_var: gateway_item
    label: "{{ gateway_item.key }}"
  with_dict: "{{ firewall_gateways }}"
  register: firewall_created_gateways

- name: Reload gateway config
  oxlorg.opnsense.reload:
    target: "gateway"
  when: firewall_purged_gateways.changed or firewall_created_gateways.changed

# Ask for configuring gateway groups manually
- name: Ask for manual gateway group configuration
  ansible.builtin.pause:
    prompt: "\n\nYou now need to do the gateway group configuration by hand!\n\
      The current configuration advices the following groups:\n\n\
      {{ firewall_gateway_groups | community.general.to_prettytable }}\n\
      SET PURGED GATEWAYS TO NEVER\n\n\
      Now is also a good time to go to the outbound interfaceses and set the default router\n\n\
      AFTER your done configuring everything hit <ENTER>\n\
      otherwise use <CTRL-C> and <a> to abort the playbook run...\n\n\
      You might reboot the router now for rules to be configured correctly\n\n"
  when: (firewall_purged_gateways.changed or firewall_created_gateways.changed) and firewall_gateway_groups | length > 0
