---
- name: Include task validate.yml
  ansible.builtin.include_tasks: validate.yml

# including required tasks
- name: Include VLAN management
  ansible.builtin.include_tasks: vlans.yml
  when: firewall_vlans.keys() | length > 0

- name: Include gateway management
  ansible.builtin.include_tasks: gateways.yml
  when: firewall_gateways.keys() | length > 0

# # - name: Include tailscale management
# #   ansible.builtin.include_tasks: tailscale.yml
# #   when: firewall_tailscale_advertised_routes | length > 0

- name: Include dhcp management
  ansible.builtin.include_tasks: dhcp.yml
  when: firewall_dhcp.keys() | length > 0

- name: Include alias management
  ansible.builtin.include_tasks: aliases.yml
  when: firewall_aliases.keys() | length > 0

- name: Include NAT management
  ansible.builtin.include_tasks: nat.yml
  when: firewall_nat_outbound.keys() | length > 0

- name: Include shaper management
  ansible.builtin.include_tasks: shaper.yml
  when: firewall_shaper_pipes.keys() | length > 0

- name: Include rule management
  ansible.builtin.include_tasks: rules.yml
  when: firewall_rules.keys() | length > 0
# ---

# - name: Include task from tls
#   ansible.builtin.include_tasks: tls.yml
