---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Create local directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
  with_items:
    - "{{ cert_private_key_path | dirname }}"
    - "{{ cert_certificate_path | dirname }}"

- name: Create user vault if not exists
  ansible.builtin.user:
    name: "{{ self_signed_certificate_vault_user }}"
    state: present
    create_home: false
    shell: "/sbin/nologin"

- name: Create group vault if not exists
  ansible.builtin.group:
    name: "{{ self_signed_certificate_vault_group }}"
    state: present

- name: Incluse task to generate CA certificate
  ansible.builtin.import_tasks: ca.yml

- name: Include task to generate domain certificate
  ansible.builtin.import_tasks: certificate.yml
