---
- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ _file }}"
  vars:
    _file: "{{ lookup('first_found', _params) }}"
    _params:
      files:
        - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_release'] | default('') }}.yml"
        - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - fallback.yml
      paths:
        - "{{ role_path }}/vars"

- name: Validate OS is supported
  ansible.builtin.assert:
    that:
      - self_signed_certificate_cert_os_is_supported
    fail_msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} is not supported."
    success_msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} is from a supported OS family."

- name: Indicate OS is tested
  when:
    - self_signed_certificate_cert_os_is_tested
  ansible.builtin.debug:
    msg: "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} has been tested with this role."

- name: Warn if OS is not tested
  when:
    - not self_signed_certificate_cert_os_is_tested
  ansible.builtin.debug:
    msg: "WARNING: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} is not tested."
  changed_when: true

- name: Validate private key path is defined
  when:
    - cert_private_key_path is defined
    - cert_private_key_path | length > 0
  ansible.builtin.assert:
    that:
      - cert_private_key_path is defined
    fail_msg: Private key path is not defined.
    success_msg: Private key path is defined.

- name: Validate certificate path is defined
  when:
    - cert_certificate_path is defined
    - cert_certificate_path | length > 0
  ansible.builtin.assert:
    that:
      - cert_certificate_path is defined
    fail_msg: Certificate path is not defined.
    success_msg: Certificate path is defined.
