---
- name: Create required base directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/docker"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Create required compose directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/docker/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy docker-compose file for {{ item }}
  ansible.builtin.template:
    src: docker-compose-{{ item }}.yml.j2
    dest: "/home/{{ ansible_user }}/docker/{{ item }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Create and start service
  community.docker.docker_compose_v2:
    project_src: docker/{{ item }}
  register: docker_output

- name: Show results only if verbose mode is enabled
  # when: ansible_verbosity > 0
  ansible.builtin.debug:
    var: docker_output
