---
- name: Set repository name fact
  ansible.builtin.set_fact:
    __compose_remote_repo_name: "{{ compose_remote_url | urlsplit('path') | basename | regex_replace('\\.git$', '') }}"

- name: Clone remote docker-compose repository
  ansible.builtin.git:
    repo: "{{ compose_remote_url }}"
    dest: "/home/{{ ansible_user }}/{{ __compose_remote_repo_name }}"
    version: main
    update: true
  become: true
  become_user: "{{ ansible_user }}"

- name: Write .env file for remote stack
  ansible.builtin.copy:
    content: "{{ item.envs | join('\n') }}\n"
    dest: "/home/{{ ansible_user }}/{{ __compose_remote_repo_name }}/{{ item.name }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  loop: "{{ compose_remote_stacks }}"
  loop_control:
    label: "{{ item.name }}"

- name: Deploy remote compose stack
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}/{{ __compose_remote_repo_name }}/{{ item.name }}"
    state: present
  loop: "{{ compose_remote_stacks }}"
  loop_control:
    label: "{{ item.name }}"
