---
- name: Include role geerlin
  ansible.builtin.include_role:
    name: geerlingguy.docker

- name: Include task to deploy compose files for services
  ansible.builtin.include_tasks: compose.yml
  loop: "{{ docker_deploy_stacks }}"
  loop_control:
    loop_var: item
