---
- name: Include role geerlin
  ansible.builtin.include_role:
    name: geerlingguy.docker

- name: Include task to deploy compose files for services
  ansible.builtin.include_tasks: compose.yml
  loop: "{{ docker_deploy_stacks }}"
  loop_control:
    loop_var: item

- name: Include task to deploy compose remote files for services
  ansible.builtin.include_tasks: compose_remote.yml
  when: compose_remote_stacks is defined and compose_remote_stacks | length > 0
