---
- name: Create required directories for Docker compose
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/docker"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy portainer docker-compose-portainer.yml file
  ansible.builtin.template:
    src: docker-compose-portainer.yml.j2
    dest: /home/{{ ansible_user }}/docker/docker-compose-portainer.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Create and start service
  community.docker.docker_compose_v2:
    project_src: docker
    files: "/home/{{ ansible_user }}/docker/docker-compose-portainer.yml"
  register: docker_output

- name: Show results only if verbose mode is enabled
  when: ansible_verbosity > 0
  ansible.builtin.debug:
    var: docker_output
