---
self_signed_certificate_organization_name: "Self-Signed Organisation"
self_signed_certificate_ownca_not_after: "+3650d"
self_signed_certificate_vault_user: vault
self_signed_certificate_vault_group: vault
