---
# defaults file for sflab.homelab.technitium

# Set to true to automatically store Technitium TSIG key in Vault KV. Requires Vault connection details and AppRole credentials to be set.
technitium_store_tsig_key: false

# KV v2 engine mount point (must already exist in Vault).
vault_kv_engine_name: "secrets_homelab"

# Path inside the KV engine where the token is stored.
vault_kv_path: "technitium"
