---
- name: Include task from postgresql.yml
  include_tasks: postgres.yml

- name: Include task from redis.yml
  include_tasks: redis.yml

- name: Include task from install.yml
  include_tasks: install.yml
